export const ColorTags = {
  SLATE: 'SLATE',
  GRAY: 'GRAY',
  ZINC: 'ZINC',
  NEUTRAL: 'NEUTRAL',
  STONE: 'STONE',
  RED: 'RED',
  ORANGE: 'ORANGE',
  AMBER: 'AMBER',
  YELLOW: 'YELLOW',
  LIME: 'LIME',
  GREEN: 'GREEN',
  EMERALD: 'EMERALD',
  TEAL: 'TEAL',
  CYAN: 'CYAN',
  SKY: 'SKY',
  BLUE: 'BLUE',
  INDIGO: 'INDIGO',
  VIOLET: 'VIOLET',
  PURPLE: 'PURPLE',
  FUCHSIA: 'FUCHSIA',
  PINK: 'PINK',
  ROSE: 'ROSE',
};

export const colorToClasses = {
  [ColorTags.SLATE]: 'bg-slate-600 text-slate-900',
  [ColorTags.GRAY]: 'bg-gray-600 text-gray-900',
  [ColorTags.ZINC]: 'bg-zinc-600 text-zinc-900',
  [ColorTags.NEUTRAL]: 'bg-neutral-600 text-neutral-900',
  [ColorTags.STONE]: 'bg-stone-600 text-stone-900',
  [ColorTags.RED]: 'bg-red-600 text-red-900',
  [ColorTags.ORANGE]: 'bg-orange-600 text-orange-900',
  [ColorTags.AMBER]: 'bg-amber-600 text-amber-900',
  [ColorTags.YELLOW]: 'bg-yellow-600 text-yellow-900',
  [ColorTags.LIME]: 'bg-lime-600 text-lime-900',
  [ColorTags.GREEN]: 'bg-green-600 text-green-900',
  [ColorTags.EMERALD]: 'bg-emerald-600 text-emerald-900',
  [ColorTags.TEAL]: 'bg-teal-600 text-teal-900',
  [ColorTags.CYAN]: 'bg-cyan-600 text-cyan-900',
  [ColorTags.SKY]: 'bg-sky-600 text-sky-900',
  [ColorTags.BLUE]: 'bg-blue-600 text-blue-900',
  [ColorTags.INDIGO]: 'bg-indigo-600 text-indigo-900',
  [ColorTags.VIOLET]: 'bg-violet-600 text-violet-900',
  [ColorTags.PURPLE]: 'bg-purple-600 text-purple-900',
  [ColorTags.FUCHSIA]: 'bg-fuchsia-600 text-fuchsia-900',
  [ColorTags.PINK]: 'bg-pink-600 text-pink-900',
  [ColorTags.ROSE]: 'bg-rose-600 text-rose-900',
};
